ag=e=>{let t=Math.min(Math.max(l.x,0),1),a=0,n=!1;
e9&&(a=e9.x,n=!0,.004>Math.abs(e9.t-e9.x)&&.015>Math.abs(e9.v)&&(e9=null,t7=!1,a=0,n=!1)),tt+=(!!W.current-tt)*td(.12);
let p=[eX(r[0],s[0],t),eX(r[1],s[1],t)],f=[eZ(p[0]),eZ(p[1])],w=(f[0][0]+f[1][0])/2,U=(f[0][1]+f[1][1])/2,F=(114.2705-w)*.42*tt,L=(114.2705-U)*.42*tt,S=E.x>.001||Math.abs(ed.t-ed.x)>.01;
null!==t6&&(a+=t6,n=!0);
let V=S?ed.x:null;
V=n?(V??0)+a:V;
let Q=eA(en.current);
if(en.current!==y){let e=ty(tC(C.x,0,1)),t=eA(y);
M=e>=1?t.ring:eT(M,t.ring,e),v=e>=1?t.face:tQ(v,t.face,e),j+=(t.tiltScale-j)*e,k+=(t.beltRadius-k)*e,y=en.current,C.x=0,C.v=0,C.t=1,i||(t7=!1,0==(t5=(t5+1)%5)?tp(1):1===t5?(t7=!0,tp(2)):2===t5?t4("spinBounce"):3===t5?t4("spinDizzy"):(tp(1),tI.burst(16,.95,.3)))}let P=ty(tC(C.x,0,1)),z=P<.999,T=z?eT(M,Q.ring,P):Q.ring,Y=z?tQ(v,Q.face,P):Q.face,ee=X.current,et=Z.current,ea=J.current,ei={x:Y.x,y:Y.y,sx:Y.sx*(ee?.gap??1),sy:Y.sy*(ee?.height??1),eye:Y.eye*(ee?.size??1),leftDX:Y.leftDX??0},er=(e,t,a)=>{let i=Math.PI/180,r=Math.cos(e*i),s=Math.sin(e*i),l=Math.cos(t*i),n=Math.sin(t*i),d=Math.cos(a*i),o=Math.sin(a*i);
return[d*r-o*n*s,-o*l,d*s+o*n*r,o*r+d*n*s,d*l,o*s-d*n*r,-l*s,n,l*r]},es=null;
if(ea){let e=q.current,t=er(et.turn,et.tilt,et.roll),a=er(e.turn,e.tilt,e.roll);
es=[t[0]*a[0]+t[1]*a[1]+t[2]*a[2],t[0]*a[3]+t[1]*a[4]+t[2]*a[5],t[0]*a[6]+t[1]*a[7]+t[2]*a[8],t[3]*a[0]+t[4]*a[1]+t[5]*a[2],t[3]*a[3]+t[4]*a[4]+t[5]*a[5],t[3]*a[6]+t[4]*a[7]+t[5]*a[8],t[6]*a[0]+t[7]*a[1]+t[8]*a[2],t[6]*a[3]+t[7]*a[4]+t[8]*a[5],t[6]*a[6]+t[7]*a[7]+t[8]*a[8]]}let el=z?j+(Q.tiltScale-j)*P:Q.tiltScale;
R=z?k+(Q.beltRadius-k)*P:Q.beltRadius,"loading"===em.current&&(R+=(52-R)*tC(E.x,0,1));
let ey=T[Math.round(7*T.length/8)%T.length],eM=!1;
n&&!z&&Q.turnAt&&(T=Q.turnAt(a),eM=!0);
let ew=Q.top,ev=Q.bottom;
if(z||eM)for(let e of(ew=1/0,ev=-1/0,T))e[1]<ew&&(ew=e[1]),e[1]>ev&&(ev=e[1]);
let ej=z||eM?e=>((e,t)=>{let a=-1/0,i=1/0;
for(let r=0;
r<e.length;
r++){let s=e[r],l=e[(r+1)%e.length];
if(s[1]<=t==l[1]<=t)continue;
let n=s[0]+(l[0]-s[0])*(t-s[1])/(l[1]-s[1]);
n<=114.2705?n>a&&(a=n):n<i&&(i=n)}return tP[0]=Number.isFinite(a)?a:114.2705,tP[1]=Number.isFinite(i)?i:114.2705,tP})(T,e):Q.spanAt,ek=0,eR=0;
for(let e of p[0])ek=Math.max(ek,Math.abs(e[0]-f[0][0]));
for(let e of p[1])eR=Math.max(eR,Math.abs(e[0]-f[1][0]));
let eE=$.current,eN=eE?ei.leftDX??0:0,eI=Math.abs(f[1][0]-(f[0][0]+eN))*ei.sx,eB=ek+eR>.5?tC((eI-5*!eE)/(ek+eR),.35,4):4,eU=[0,0];
if("working"===em.current&&null!==V&&("pebble"===en.current||"tablet"===en.current||"cloud"===en.current)){let e=f.map(([e,t],a)=>{let[i,r]=ej(tC(114.2705+ei.y+(t-114.2705)*ei.sy,ew+2,ev-2)),s=Math.max((r-i)/2,12),l=Math.asin(tC((e+(0===a?eN:0)-114.2705)*ei.sx/s,-1,1))+V;
return{x:(i+r)/2+s*Math.sin(l),visible:Math.cos(l)>.02}});
if(e[0].visible&&e[1].visible){let t=e[1].x-e[0].x;
if(t<eI){let e=(eI-t)/2;
eU[0]=-e,eU[1]=e}}}for(let a=0;
a<2;
a++){let i=eu.current[a];
if(!i)continue;
let[r,s]=f[a],l=Math.max(c.x,.04);
if(a===m&&e<b+320){let t=(e-b)/320;
l=Math.max(l*(t<.42?1-t/.42:(t-.42)/.58),.04)}let n=p[a],d=n;
if(Math.abs(l-1)>.001){let e=0,t=0,a=0;
for(let i=0;
i<n.length;
i++){let l=n[i][0]-r,d=n[i][1]-s;
e+=l*l,t+=d*d,a+=l*d}let i=Math.hypot(e-t,2*a)/Math.max(e+t,1e-6),o=.5*Math.atan2(2*a,e-t),A=Math.cos(o),h=Math.sin(o);
h<0&&(A=-A,h=-h);
let c=tv(tC((i-.12)/.18,0,1)),u=Math.hypot(A*=c,h=h*c+(1-c))||1;
A/=u,h/=u;
let g=1-l;
d=n.map(([e,t])=>{let a=(e-r)*A+(t-s)*h;
return[e-a*g*A,t-a*g*h]})}i.setAttribute("d",eY(d));
let o=r+(0===a?eN:0),A=114.2705+ei.x,h=(o-114.2705)*ei.sx,C=tC(114.2705+ei.y+(s-114.2705)*ei.sy,ew+2,ev-2),y=1,M=1,w=1,v=0,j=0,k=1,R=!0,N=1,I=null!==V||ea;
if(ea&&es){let e=(o-114.2705)/114.2705,t=(114.2705-s)/114.2705,a=Math.sqrt(Math.max(0,1-e*e-t*t))||.02,i=es[0]*e+es[1]*t+es[2]*a,r=es[3]*e+es[4]*t+es[5]*a,l=es[6]*e+es[7]*t+es[8]*a;
h=114.2705*i*ei.sx,C=tC(114.2705+ei.y-114.2705*r*ei.sy,ew+2,ev-2);
let n=-t*e,d=1-t*t,A=-t*a,c=Math.hypot(n,d,A);
c<1e-6?(n=0,d=0,A=1):(n/=c,d/=c,A/=c);
let u=t*A-a*d,g=a*n-e*A,x=e*d-t*n,p=es[0]*n+es[1]*d+es[2]*A,f=es[3]*n+es[4]*d+es[5]*A,b=es[0]*u+es[1]*g+es[2]*x,m=es[3]*u+es[4]*g+es[5]*x,E=-g,I=n,B=-d,U=u*B-I*E||1e-6,F=B/U,L=-I/U,S=-E/U,V=u/U,D=-m,H=-f;
w=b*F+p*S,j=b*L+p*V,v=D*F+H*S,k=D*L+H*V,y=Math.max(Math.hypot(w,v),.02),M=Math.max(Math.hypot(j,k),.02),R=l>.02,N=tv(tC(l/.5,0,1))}if(null!==V){let e=V,[t,a]=ej(C),i=Math.max((a-t)/2,12);
A=(t+a)/2;
let r=Math.asin(tC(h/i,-1,1)),s=r+e,l=Math.cos(s),n=Math.max(Math.cos(r),.02);
R=l>.02,y=Math.max(l,.02)/n,h=i*Math.sin(s),N=tv(tC(l/.5,0,1))}let B=1+.07*Math.sin(t*Math.PI),U=0,S=0;
G.current&&(U=1.4*Math.sin(42e-5*e+a)+.5*Math.sin(.001*e+2*a),S=.9*Math.sin(58e-5*e+a));
let H=O.current;
if(H&&D.current){(!e6||e-e5>200)&&(e6=D.current.getBoundingClientRect(),e5=e);
let t=e6;
te.tx=22*tC((H.x-(t.left+t.width/2))/t.width,-.6,.6),te.ty=14*tC((H.y-(t.top+t.height/2))/t.height,-.6,.6)}else te.tx=0,te.ty=0;
let Q=td(.16);
te.x+=(te.tx-te.x)*Q,te.y+=(te.ty-te.y)*Q,U+=te.x*(1-.6*tt)+F,S+=te.y*(1-.6*tt)+L;
let P=H?.2:1;
U+=g.x*P+t1,S+=x.x*P+t0;
let W=tC(eP.x,0,1);
U-=10*W,S+=7*W;
let K=($.current?1:ei.eye)*tC(_.current,.25,4),z=Math.min(tC(u.x,.2,2)*K,eB/B),T=1===a?ee?.eyeWidthRight??ee?.eyeWidth??1:ee?.eyeWidth??1,Y=1===a?ee?.eyeHeightRight??ee?.eyeHeight??1:ee?.eyeHeight??1,Z=Math.min(z*tC(T,.2,3),eB/B),J=z*tC(Y,.2,3),q=tC(y*Z*B,.02,2.4),X=tC(M*J*B,.02,2.4);
i.style.display=R&&E.x<.5?"":"none";
let et=21*X+2,er=tC(I?C+S*ei.sy:114.2705+ei.y+(s+S-114.2705)*ei.sy,ew+et,ev-et),el=-1/0,ed=1/0;
for(let e=0;
e<d.length;
e+=2){let t=(d[e][0]-r)*q,[a,i]=ej(er+(d[e][1]-s)*X);
a-t>el&&(el=a-t),i-t<ed&&(ed=i-t)}let eo=A+h+eU[a]+U*ei.sx,eA=el<=ed?tC(eo,el,ed):(el+ed)/2,eh=eA+(eo-eA)*(1-N),ec=er;
if(eP.x>.01){let e=20*tC(eP.x,0,1.4),t=eh-ey[0],i=ec-ey[1],r=Math.hypot(t,i)||1,s=t/r,l=i/r,n=e+Math.hypot((0===a?ek:eR)*q*s,21*X*l)+5;
r<n&&(eh+=s*(n-r),ec+=l*(n-r))}if(ea&&es){let e=tC(Z*B,.02,2.4),t=tC(J*B,.02,2.4),a=null!==V&&("cloud"===en.current||"pebble"===en.current||"tablet"===en.current)?y:1,l=w*e*a,n=v*e,d=j*t*a,o=k*t;
i.setAttribute("transform",`translate(${eh.toFixed(2)} ${ec.toFixed(2)}) matrix(${l.toFixed(4)} ${n.toFixed(4)} ${d.toFixed(4)} ${o.toFixed(4)} 0 0) translate(${(-r).toFixed(2)} ${(-s).toFixed(2)})`)}else i.setAttribute("transform",`translate(${eh.toFixed(2)} ${ec.toFixed(2)}) scale(${q.toFixed(4)} ${X.toFixed(4)}) translate(${(-r).toFixed(2)} ${(-s).toFixed(2)})`)}let eF=tC(E.x,0,1),eL=tC(N.x,0,1),eS=eL<.999?B:null,eV=tC(eF/.62,0,1),eD="pencil"===I||"pencil"===eS,eO=eD?eL>=.999?tS(I):eT(tS(eS),tS(I),ty(eL)):ts;
if(eM||tz||eV!==tW||P!==tK||en.current!==tG||eD||Q.path!==tT){let e=eo.current&&eV<=0&&!z,t=eV>=1?eD?e4(eO):tF:e||eV<=0&&!z&&!eM?Q.path:e4(eV<=0?T:eT(T,eO,ty(eV)));
eh.current?.setAttribute("d",t),ec.current?.setAttribute("d",t),tW=eV,tK=P,tz=eM,tG=en.current,tT=Q.path}for(let e of ef.current)e&&(e.style.display="none");
for(let e of eb.current)e&&(e.style.display="none");
for(let e of eg.current)e&&(e.style.display="none");
for(let e of ep.current)e&&(e.style.display="none");
let eW=e=>null==e?0:e===I?eF*eL:e===eS?eF*(1-eL):0,eK={dots:22,orbit:19,radar:19,progress:19,gather:19,wave:16,send:20,receive:20,dock:20,ball:18,whirl:15,pencil:17,bang:13,standby:13},ez=I?eK[I]*eL+(eS?eK[eS]:eK[I])*(1-eL):19,eG=ae(e,1,eF),eJ="dots"===I||"dots"===eS,eq=eW("dots"),e$=eJ?1+(eG.pop-1)*(eq/Math.max(eF,.001)):1,e_=e-eC.current,e1=eW("receive");
e1>.004&&(e$*=1+.11*Math.sin(tC(((e_/1700%1+1)%1-.58)/.34,0,1)*Math.PI)*e1);
let e0=eW("send");
if(e0>.004){let e=(e_/1500%1+1)%1;
e$*=1+((e<.18?-.06*Math.sin(e/.18*Math.PI):0)+(e>=.18&&e<.42?.05*Math.sin((e-.18)/.24*Math.PI):0))*e0}let e3=eW("bang");
e3>.004&&(e$*=1+.04*Math.exp(-(e_/1e3%2.2*5.5))*e3);
let e2=0,e7=0,e8=0,ta=eW("pencil");
if(ta>.004){let t=aA(e);
e2+=t.x*ta,e7+=(t.y+.5*t.wig)*ta,e8+=t.rot*ta}e3>.004&&(e7+=58*e3);
let ti=eW("whirl");
if(ti>.004){let t=e/1e3;
e2+=(2*Math.sin(.9*t)+.8*Math.sin(1.7*t))*ti,e7+=(2.4*Math.sin(1.3*t)+1.2*Math.sin(.6*t))*ti}let tn=eW("ball");
if(tn>.004){let t,a=(e-eC.current)/1e3,i=416/.3844,r=Math.sqrt(80/(416/.3844));
if(a<r)t=40-.5*i*a*a;
else{let e=((a-r)/.62%1+1)%1;
t=208*e*(1-e)}e7+=(40-t)*tn}let to=ez/114.2705*e$;
if(H.current){let t=1-eF,a=o.x*t+tX*t+e2*eF,i=(A.x+tJ)*t+t$*t-eG.lift*eq+e7*eF,r=(d.x*t+tq*t)*el+t_*t+e8*eF,s=t+to*eF,l=h.x*t+to*eF;
H.current.setAttribute("transform",`translate(${(114.2705+a).toFixed(2)} ${(114.2705+i).toFixed(2)}) rotate(${r.toFixed(2)}) scale(${s.toFixed(4)} ${l.toFixed(4)}) translate(-114.2705 -114.2705)`);
let n=eW("standby"),c=n>0?(.28+.2*Math.sin(.0016*e))*n:0;
H.current.style.opacity=((1-(1-eG.tone)*eq)*(1-c)).toFixed(3)}if(eP.t=+("notifying"===em.current),ex.current){let e=tC(eP.x,0,1.4);
e<=.01?ex.current.style.display="none":(ex.current.style.display="",ex.current.style.fill=K.current,ex.current.setAttribute("cx",ey[0].toFixed(1)),ex.current.setAttribute("cy",ey[1].toFixed(1)),ex.current.setAttribute("r",(20*e).toFixed(2)))}for(let t of tB){let a=eW(t);
a<=.004||("dots"===t?at(a,e):"orbit"===t?aa(a,e):"radar"===t?ai(a,e,ez):"progress"===t?ar(a,e):"gather"===t?as(a,e):"wave"===t?al(a,e):"send"===t?an(a,e):"receive"===t?ad(a,e):"doc