#!/usr/bin/env python3
"""Build-time asset pipeline for Day 17.

Downloads the 151 original-generation sprites and species data from
PokeAPI, converts sprites to RGB565 C arrays, and generates
firmware/main/generated/{sprites.c,dex_data.c,dex.h}. Generated files
are gitignored: assets are fetched at build time, never committed.

Requires: requests, Pillow.  Usage: python3 scripts/fetch-assets.py
"""
import json
import time
from pathlib import Path

import requests
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "firmware" / "main" / "generated"
CACHE = ROOT / ".build" / "asset-cache"
COUNT = 151
SIZE = 96

SPRITE_URL = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/{id}.png"
DATA_URL = "https://pokeapi.co/api/v2/pokemon/{id}"


def fetch(url, path):
    if path.exists():
        return path.read_bytes()
    for attempt in range(3):
        try:
            r = requests.get(url, timeout=30)
            r.raise_for_status()
            path.write_bytes(r.content)
            return r.content
        except Exception as e:
            print(f"  retry {attempt + 1}: {url} ({e})")
            time.sleep(2)
    raise RuntimeError(f"failed: {url}")


def rgb565(im):
    """PNG (with transparency) -> RGB565 little-endian bytes on black."""
    im = im.convert("RGBA")
    bg = Image.new("RGBA", im.size, (0, 0, 0, 255))
    im = Image.alpha_composite(bg, im).convert("RGB")
    if im.size != (SIZE, SIZE):
        im = im.resize((SIZE, SIZE), Image.NEAREST)
    out = bytearray()
    for r, g, b in im.getdata():
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        out += v.to_bytes(2, "little")
    return bytes(out)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    CACHE.mkdir(parents=True, exist_ok=True)

    entries = []
    sprites_c = ["// GENERATED by scripts/fetch-assets.py — do not commit.",
                 "#include <stdint.h>", ""]
    for i in range(1, COUNT + 1):
        png = fetch(SPRITE_URL.format(id=i), CACHE / f"{i}.png")
        data = json.loads(fetch(DATA_URL.format(id=i), CACHE / f"{i}.json"))
        name = data["species"]["name"].capitalize()
        types = [t["type"]["name"].capitalize() for t in data["types"]]
        stats = {s["stat"]["name"]: s["base_stat"] for s in data["stats"]}
        entries.append({
            "name": name,
            "type1": types[0],
            "type2": types[1] if len(types) > 1 else "",
            "height": data["height"],  # decimeters
            "weight": data["weight"],  # hectograms
            "hp": stats["hp"], "attack": stats["attack"],
            "defense": stats["defense"], "speed": stats["speed"],
        })
        pixels = rgb565(Image.open(CACHE / f"{i}.png"))
        words = ",".join(str(int.from_bytes(pixels[j:j+2], "little"))
                         for j in range(0, len(pixels), 2))
        sprites_c.append(
            f"const uint16_t dex_sprite_{i}[{SIZE * SIZE}] = {{{words}}};")
        if i % 25 == 0:
            print(f"  {i}/{COUNT}")

    sprites_c.append("")
    sprites_c.append(f"const uint16_t *const dex_sprites[{COUNT}] = {{")
    sprites_c.append(",".join(f"dex_sprite_{i}" for i in range(1, COUNT + 1)))
    sprites_c.append("};")
    (OUT / "sprites.c").write_text("\n".join(sprites_c))

    dex_c = ["// GENERATED by scripts/fetch-assets.py — do not commit.",
             '#include "dex.h"', "",
             f"const dex_entry_t dex_entries[{COUNT}] = {{"]
    for e in entries:
        dex_c.append(
            f'  {{"{e["name"]}", "{e["type1"]}", "{e["type2"]}", '
            f'{e["height"]}, {e["weight"]}, {e["hp"]}, {e["attack"]}, '
            f'{e["defense"]}, {e["speed"]}}},')
    dex_c.append("};")
    (OUT / "dex_data.c").write_text("\n".join(dex_c))

    (OUT / "dex.h").write_text(f"""// GENERATED by scripts/fetch-assets.py — do not commit.
#pragma once
#include <stdint.h>

#define DEX_COUNT {COUNT}
#define DEX_SPRITE_SIZE {SIZE}

typedef struct {{
    const char *name;
    const char *type1;
    const char *type2; // empty string when single-typed
    uint16_t height_dm;
    uint16_t weight_hg;
    uint8_t hp, attack, defense, speed;
}} dex_entry_t;

extern const dex_entry_t dex_entries[DEX_COUNT];
extern const uint16_t *const dex_sprites[DEX_COUNT];
""")
    total = sum((CACHE / f"{i}.png").stat().st_size for i in range(1, COUNT + 1))
    print(f"done: {COUNT} sprites, {COUNT * SIZE * SIZE * 2 / 1048576:.1f} MB "
          f"of RGB565 (from {total / 1048576:.1f} MB of PNG)")


if __name__ == "__main__":
    main()
